version: '3'
services:
  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=caching_sha2_password
    environment:
      MYSQL_ROOT_PASSWORD: '8079'
      MYSQL_DATABASE: 'movieTracker'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'pass'
    ports:
      - 3306:3306